language: node_js

node_js:
  - "5"

before_script:
  - npm install -g bower gulp-cli mocha
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm run test-client
  # - gulp coverage_frontend
  # - npm run-script test-on-travis

services: mongodb
