language: node_js

node_js:
  - "5"

before_script:
  - npm install -g bower gulp-cli mocha
  - bower install
  - npm run test-client
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - gulp coverage_frontend
  - npm run-script test-on-travis

services: mongodb
